language: python
python:
- '3.6'
services:
- docker
env:
  global:
  - SERVICE_UUID=008562a7-4a31-474b-ab11-d177510fe88e
  - AOS_UPLOAD_SERVICE_URL=https://aoscloud.io:10000/api/v1/services/versions/
  - SP_CERTIFICATE=meta_folder/sp-client.pem
  - PRIVATE_KEY=meta_folder/private_key.pem
install:
- pip install docker-compose
- sudo apt-get install curl
- mkdir package
script:
- docker pull aoscloud/aos_signer:1.0.0
- docker run -v $(pwd)/meta_folder:/data/meta/ -v $(pwd)/src/:/data/src/ -v $(pwd)/package:/data/package
  aoscloud/aos_signer:1.0.0
- curl --request POST -k -v --cacert meta_folder/rootCA.crt.pem --cert $SP_CERTIFICATE
  --key $PRIVATE_KEY --form "service=$SERVICE_UUID" --form "file=@package/service.tar.gz"
  $AOS_UPLOAD_SERVICE_URL
before_install:
- openssl aes-256-cbc -K $encrypted_76936a6256ee_key -iv $encrypted_76936a6256ee_iv
  -in meta_folder/private_key.pem.enc -out meta_folder/private_key.pem -d
